import React, { useState } from 'react';
import { 
  View, 
  Text, 
  TextInput, 
  TouchableOpacity, 
  ScrollView, 
  ActivityIndicator,
  Alert 
} from 'react-native';
import { useRouter } from 'expo-router';
import { GlassCard } from '../../components/ui/GlassCard';
import { ProjectService, Project } from '../../services/api';
import { Wand2, Check, ArrowLeft, ChevronRight } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import Animated, { FadeInDown, Layout } from 'react-native-reanimated';

/**
 * Screen: Advanced AI-Native Add Project
 * Creative UI/UX Role + Backend Guru Integration
 */
export default function AddProjectScreen() {
  const router = useRouter();
  const [nlpText, setNlpText] = useState('');
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  
  // Local state for the "Draft" generated by AI
  const [draft, setDraft] = useState<Partial<Project> | null>(null);

  const handleAiGenerate = async () => {
    if (!nlpText.trim()) {
      Alert.alert('אופס', 'נא להזין רעיון לפרויקט כדי שאוכל לעזור');
      return;
    }

    setGenerating(true);
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    
    try {
      const generatedData = await ProjectService.aiGenerate(nlpText);
      setDraft(generatedData);
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    } catch (err) {
      Alert.alert('שגיאת AI', 'לא הצלחתי לנתח את הפרויקט, נסה שוב');
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!draft || !draft.name) return;
    
    setLoading(true);
    try {
      const saved = await ProjectService.create(draft);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      router.replace(`/(tabs)`);
    } catch (err) {
      Alert.alert('שגיאה', 'שמירת הפרויקט נכשלה');
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView className="flex-1 bg-slate-950" contentContainerStyle={{ paddingBottom: 40 }}>
      {/* Mesh Gradient Background (Mock) */}
      <View 
        className="absolute top-0 left-0 right-0 h-80 opacity-40"
        style={{ 
          backgroundColor: draft?.themeColor || '#4f46e5',
        }}
      />

      <View className="px-6 pt-16">
        <TouchableOpacity onPress={() => router.back()} className="mb-8">
          <ArrowLeft color="white" size={24} />
        </TouchableOpacity>

        <Animated.View entering={FadeInDown.duration(400)}>
          <Text className="text-white text-3xl font-bold mb-2 text-right">
            צור פרויקט חדש עם AI
          </Text>
          <Text className="text-slate-400 text-lg mb-8 text-right">
            תאר את הרעיון שלך במילים חופשיות
          </Text>
        </Animated.View>

        {/* NLP Input Area */}
        <GlassCard className="mb-6">
          <TextInput
            placeholder="לדוגמה: לבנות אפליקציית מוזיקה מבוססת בינה מלאכותית..."
            placeholderTextColor="#94a3b8"
            multiline
            numberOfLines={4}
            value={nlpText}
            onChangeText={setNlpText}
            className="text-white text-right text-lg min-h-[100px]"
            style={{ textAlignVertical: 'top' }}
          />
          
          <TouchableOpacity 
            onPress={handleAiGenerate}
            disabled={generating}
            className={`mt-4 flex-row justify-center items-center py-4 rounded-2xl ${generating ? 'bg-indigo-900' : 'bg-indigo-600'}`}
          >
            {generating ? (
              <ActivityIndicator color="white" size="small" />
            ) : (
              <>
                <Text className="text-white font-bold text-lg mr-2">תחולל קסם עם AI</Text>
                <Wand2 color="white" size={20} />
              </>
            )}
          </TouchableOpacity>
        </GlassCard>

        {/* AI Draft Preview */}
        {draft && (
          <Animated.View 
            entering={FadeInDown.duration(600)} 
            layout={Layout.springify()}
            className="mt-6"
          >
            <Text className="text-white text-xl font-semibold mb-4 text-right">הצעה של ה-Helper:</Text>
            
            <GlassCard 
              style={{ borderColor: draft.themeColor }}
              className="mb-8 border-2"
            >
              <View className="items-end mb-4">
                <Text className="text-white text-2xl font-bold">{draft.name}</Text>
                <Text className="text-slate-300 text-right mt-1">{draft.description}</Text>
              </View>

              <View className="bg-slate-800/50 h-px w-full my-4" />

              <Text className="text-indigo-400 font-bold mb-3 text-right">משימות מומלצות:</Text>
              {draft.metadata?.suggestedSubtasks?.map((task, index) => (
                <View key={index} className="flex-row-reverse items-center mb-2">
                  <View className="h-2 w-2 rounded-full bg-indigo-500 ml-3" />
                  <Text className="text-slate-300 text-right">{task}</Text>
                </View>
              ))}

              <TouchableOpacity 
                onPress={handleSave}
                disabled={loading}
                className="mt-8 bg-white py-4 rounded-2xl flex-row justify-center items-center"
              >
                {loading ? (
                  <ActivityIndicator color="#0f172a" />
                ) : (
                  <>
                    <Text className="text-slate-950 font-bold text-lg mr-2">אשר וצור פרויקט</Text>
                    <Check color="#0f172a" size={20} />
                  </>
                )}
              </TouchableOpacity>
            </GlassCard>
          </Animated.View>
        )}
      </View>
    </ScrollView>
  );
}
